language: node_js
dist: xenial
os:
  - linux
  - osx
node_js:
  - "8"
  - "10"
addons:
  apt:
    packages:
    - build-essential
    - libusb-1.0-0
    - libusb-1.0-0-dev
    - libudev-dev
    - gcc-4.8
    - g++-4.8
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX=g++-4.8 ; fi
cache:
  yarn: true
env:
  - EMBARK_NO_PREPARE=true
install:
  - yarn install
  - cd embark-ui && yarn install && cd ..
  - npm run check-working-tree
script:
  - npm run build:node
  - npm test
  - npm run check-working-tree
