environment:
  matrix:
    - nodejs_version: "8"
    - nodejs_version: "10"
install:
  # get the latest version of Node.js in a release series
  - ps: Install-Product node $env:nodejs_version
  # output useful info for debugging
  - node --version
  - npm --version
  # install modules
  - npm install
test_script:
  - npm run build:node
  - npm test
build: off
